version: "3.9"

services:
  postgres:
    image: postgres:15
    container_name: news_postgres
    environment:
      POSTGRES_USER: news_user
      POSTGRES_PASSWORD: news_pass
      POSTGRES_DB: news_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - news_network

  pgadmin:
    image: dpage/pgadmin4
    container_name: news_pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin_pass
    ports:
      - "5050:80"
    volumes:
      - pgadmindata:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - news_network

  app:
    image: news:latest
    container_name: news_app
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgresql://news_user:news_pass@postgres:5432/news_db
      GOOGLE_APPLICATION_CREDENTIALS: /app/keys/key.json
    ports:
      - "8000:8000"
    depends_on:
      - postgres
    networks:
      - news_network
    volumes:
      - ./key.json:/app/keys/key.json:ro

volumes:
  pgdata:
  pgadmindata:

networks:
  news_network:
    driver: bridge

